import fs from 'node:fs/promises'; import fontkit from '@pdf-lib/fontkit'; import {PDFDocument,StandardFonts,rgb,type PDFFont,type PDFPage} from 'pdf-lib'; import type {SheetData} from '../types.js'; import {A4_LANDSCAPE_2UP_HORIZONTAL_V1 as T,mmToPt} from '../template/a4Landscape2upV1.js'; import {createQrPayload,qrDataUrl} from './qrCodeService.js';
const y=(mm:number)=>mmToPt(T.page.height-mm);
function text(page:PDFPage,font:PDFFont,s:string,x:number,top:number,size=8){page.drawText(s,{x:mmToPt(x),y:y(top)-size,size,font,color:rgb(0,0,0)});}
async function drawHalf(doc:PDFDocument,page:PDFPage,font:PDFFont,data:SheetData,offset:number,secret:string){
 const h=T.half; for(const m of h.markers) page.drawRectangle({x:mmToPt(offset+m.x-h.markerSize/2),y:y(m.y+h.markerSize/2),width:mmToPt(h.markerSize),height:mmToPt(h.markerSize),color:rgb(0,0,0)});
 const qr=await qrDataUrl(createQrPayload(data.sheetId,secret)); const img=await doc.embedPng(qr); page.drawImage(img,{x:mmToPt(offset+h.qr.x),y:y(h.qr.y+h.qr.size),width:mmToPt(h.qr.size),height:mmToPt(h.qr.size)});
 text(page,font,'GABARITO DE AVALIAÇÃO',offset+49,20,10); text(page,font,`Nº ${data.assessmentNumber}  •  ${data.assessmentYear}`,offset+49,27); text(page,font,`Disciplina: ${data.subject}`,offset+49,33); text(page,font,`Unidade: ${data.unitName}`,offset+49,39);
 text(page,font,`Aluno: ${data.studentName??'____________________________________'}`,offset+18,50); text(page,font,`Série: ${data.grade}º   Turma: ${data.className??'_______'}   Tempo: ${data.timeMode==='FULL'?'Integral':'Parcial'}`,offset+18,57);
 page.drawLine({start:{x:mmToPt(offset+18),y:y(66)},end:{x:mmToPt(offset+130),y:y(66)},thickness:.7});
 for(const row of h.questions.slice(0,data.questionCount)){text(page,font,String(row.question).padStart(2,'0'),offset+18,row.y+1,7); for(const b of row.bubbles){page.drawCircle({x:mmToPt(offset+b.x),y:y(b.y),size:mmToPt(b.r),borderWidth:.7,borderColor:rgb(0,0,0)});text(page,font,b.choice,offset+b.x+3.1,b.y+1.2,7);}}
 text(page,font,'Assinatura do aluno: ______________________________________',offset+18,178); text(page,font,`${T.id} • ${data.sheetId.slice(0,8)}`,offset+18,195,5.5);
}
export async function generateAnswerSheetPdf(data:SheetData,secret:string,fontPath?:string){const doc=await PDFDocument.create();const page=doc.addPage([mmToPt(297),mmToPt(210)]);let font;if(fontPath){try{doc.registerFontkit(fontkit);font=await doc.embedFont(await fs.readFile(fontPath),{subset:true});}catch{font=await doc.embedFont(StandardFonts.Helvetica);}}else font=await doc.embedFont(StandardFonts.Helvetica);await drawHalf(doc,page,font,data,0,secret);await drawHalf(doc,page,font,data,148.5,secret);page.drawLine({start:{x:mmToPt(148.5),y:mmToPt(5)},end:{x:mmToPt(148.5),y:mmToPt(205)},thickness:.6,dashArray:[4,3],color:rgb(.4,.4,.4)});return Buffer.from(await doc.save());}
