import fs from 'node:fs/promises';import os from 'node:os';import path from 'node:path';import crypto from 'node:crypto';import {createClient} from '@supabase/supabase-js';import {recognizeAnswer,verifyQrPayload} from '@omr/core';import {config,requiredSecret} from '../config.js';import {db} from '../db.js';import {inspectUpload} from './uploadSecurity.js';import {processImage} from './imageProcessingService.js';
import type {Prisma} from '@prisma/client';
export async function processUpload(buffer:Buffer,declaredMime:string,userId:string,organizationId:string){
 const safe=await inspectUpload(buffer,declaredMime);const id=crypto.randomUUID(),objectPath=`${userId}/${id}.${safe.ext}`,tmp=path.join(os.tmpdir(),`omr-${id}.${safe.ext}`);const supabase=createClient(config.SUPABASE_URL,requiredSecret('SUPABASE_SECRET_KEY'),{auth:{persistSession:false}});
 const {error}=await supabase.storage.from('omr-private').upload(objectPath,buffer,{contentType:safe.mime,upsert:false});if(error)throw new Error(`STORAGE_UPLOAD_FAILED: ${error.message}`);
 const processing=await db.readingProcessing.create({data:{uploadedBy:userId,status:'PROCESSING',storagePath:objectPath,mimeType:safe.mime,sha256:safe.sha256,algorithmVersion:'opencv-v1',startedAt:new Date()}});
 try{await fs.writeFile(tmp,buffer);const result=await processImage(tmp);if(!result.qrPayload||!verifyQrPayload(result.qrPayload,requiredSecret('QR_HMAC_SECRET')))throw new Error('QR_INVALID_OR_UNSIGNED');const sheet=await db.answerSheet.findFirst({where:{publicCode:result.qrPayload.sid,assessment:{unit:{organizationId}}},include:{assessment:true}});if(!sheet)throw new Error('ANSWER_SHEET_NOT_FOUND');const answers=result.answers.slice(0,sheet.assessment.questionCount).map(a=>recognizeAnswer(a.question,a.fills));const needsReview=answers.some(a=>a.status!=='MARKED'||a.confidence<.9);return await db.readingProcessing.update({where:{id:processing.id},data:{sheetId:sheet.id,status:needsReview?'REVIEW_REQUIRED':'READY',quality:result.quality,finishedAt:new Date(),answers:{create:answers.map(a=>({question:a.question,detectedChoice:a.selected,finalChoice:a.selected,status:a.status,confidence:a.confidence,fills:a.fills as unknown as Prisma.InputJsonValue}))}},include:{answers:true,sheet:{include:{assessment:true,student:true}}}});
 }catch(e){await db.readingProcessing.update({where:{id:processing.id},data:{status:'FAILED',errorCode:(e as Error).message.split(':')[0],errorDetail:(e as Error).message.slice(0,500),finishedAt:new Date()}});throw e;}finally{await fs.rm(tmp,{force:true});}
}
