import type {FastifyInstance} from 'fastify';
import z from 'zod';
import {createClient} from '@supabase/supabase-js';
import {gradeAnswers,toCsv,type Choice,type RecognizedAnswer} from '@omr/core';
import {db} from '../db.js';
import {config,requiredSecret} from '../config.js';
import {authenticate,permit} from '../plugins/auth.js';
import {createAssessment,saveAnswerKey} from '../services/assessmentService.js';
import {createSheet,sheetPdf} from '../services/answerSheetService.js';
import {processUpload} from '../services/processingService.js';
import {importStudents} from '../services/studentService.js';

const uuid=z.string().uuid();
const unitInput=z.object({name:z.string().trim().min(2).max(160),code:z.string().trim().max(30).optional()});
const classInput=z.object({unitId:uuid,name:z.string().trim().min(1).max(60),grade:z.number().int().min(1).max(9),schoolYear:z.number().int().min(2020).max(2100),timeMode:z.enum(['PARTIAL','FULL'])});
const studentInput=z.object({classId:uuid,name:z.string().trim().min(2).max(160),registration:z.string().trim().max(50).optional()});
const studentImportInput=z.object({rows:z.array(z.object({name:z.string().trim().min(2).max(160),registration:z.string().trim().max(50).optional(),unit:z.string().trim().min(1).max(160),grade:z.number().int().min(1).max(9),className:z.string().trim().min(1).max(60),timeMode:z.enum(['PARTIAL','FULL'])})).min(1).max(2000)});
const assessmentInput=z.object({scope:z.enum(['CLASS','NETWORK']).default('CLASS'),unitId:uuid.optional(),classId:uuid.nullish(),number:z.string().trim().min(1).max(30),year:z.number().int().min(2020).max(2100),grade:z.number().int().min(1).max(9),subject:z.enum(['PORTUGUESE','MATHEMATICS','SINGLE']),timeMode:z.enum(['PARTIAL','FULL','ALL']),assessmentDate:z.string().date()});
type UnitInput={name:string;code?:string};
type ClassInput={unitId:string;name:string;grade:number;schoolYear:number;timeMode:'PARTIAL'|'FULL'};
type StudentInput={classId:string;name:string;registration?:string};
type AssessmentInput={scope:'CLASS'|'NETWORK';unitId?:string;classId?:string|null;number:string;year:number;grade:number;subject:'PORTUGUESE'|'MATHEMATICS'|'SINGLE';timeMode:'PARTIAL'|'FULL'|'ALL';assessmentDate:string};
const parseInput=<T>(schema:z.ZodTypeAny,value:unknown)=>schema.parse(value) as T;
const assessmentOrg=(organizationId:string)=>({unit:{organizationId}});
async function requireUnit(id:string,organizationId:string){return db.educationalUnit.findFirstOrThrow({where:{id,organizationId}});}
async function requireClass(id:string,organizationId:string){return db.schoolClass.findFirstOrThrow({where:{id,unit:{organizationId}}});}

export async function routes(app:FastifyInstance){
 app.get('/api/health',async()=>({status:'ok',template:'A4_LANDSCAPE_2UP_HORIZONTAL_V1'}));
 app.get('/api/me',{preHandler:authenticate},r=>db.profile.findUniqueOrThrow({where:{id:r.auth.userId},include:{organization:true}}));
 app.get('/api/dashboard',{preHandler:authenticate},async r=>{const org=r.auth.organizationId;const [assessments,students,processed,corrected,avg,reviews]=await Promise.all([db.assessment.count({where:assessmentOrg(org)}),db.student.count({where:{schoolClass:{unit:{organizationId:org}}}}),db.readingProcessing.count({where:{sheet:{assessment:{unit:{organizationId:org}}},status:{in:['READY','FINALIZED']}}}),db.result.count({where:{sheet:{assessment:{unit:{organizationId:org}}}}}),db.result.aggregate({where:{sheet:{assessment:{unit:{organizationId:org}}}},_avg:{score:true}}),db.readingProcessing.count({where:{sheet:{assessment:{unit:{organizationId:org}}},status:'REVIEW_REQUIRED'}})]);return{assessments,students,processed,corrected,reviews,average:Number(avg._avg.score??0)};});

 app.get('/api/units',{preHandler:authenticate},r=>db.educationalUnit.findMany({where:{organizationId:r.auth.organizationId},orderBy:{name:'asc'}}));
 app.post('/api/units',{preHandler:permit('ADMIN','MANAGER')},r=>{const input=parseInput<UnitInput>(unitInput,r.body);return db.educationalUnit.create({data:{organizationId:r.auth.organizationId,name:input.name,code:input.code}});});
 app.patch('/api/units/:id',{preHandler:permit('ADMIN','MANAGER')},async r=>{const id=uuid.parse((r.params as {id:string}).id);await requireUnit(id,r.auth.organizationId);return db.educationalUnit.update({where:{id},data:unitInput.partial().parse(r.body)});});

 app.get('/api/classes',{preHandler:authenticate},r=>db.schoolClass.findMany({where:{unit:{organizationId:r.auth.organizationId}},include:{unit:true,_count:{select:{students:true}}},orderBy:[{schoolYear:'desc'},{grade:'asc'},{name:'asc'}]}));
 app.post('/api/classes',{preHandler:permit('ADMIN','MANAGER')},async r=>{const input=parseInput<ClassInput>(classInput,r.body);await requireUnit(input.unitId,r.auth.organizationId);return db.schoolClass.create({data:{unitId:input.unitId,name:input.name,grade:input.grade,schoolYear:input.schoolYear,timeMode:input.timeMode}});});
 app.get('/api/students',{preHandler:authenticate},r=>db.student.findMany({where:{schoolClass:{unit:{organizationId:r.auth.organizationId}}},include:{schoolClass:{include:{unit:true}}},orderBy:{name:'asc'}}));
 app.post('/api/students',{preHandler:permit('ADMIN','MANAGER','TEACHER')},async r=>{const input=parseInput<StudentInput>(studentInput,r.body);await requireClass(input.classId,r.auth.organizationId);return db.student.create({data:{classId:input.classId,name:input.name,registration:input.registration}});});
 app.post('/api/students/import',{preHandler:permit('ADMIN','MANAGER','TEACHER','OPERATOR')},async r=>{const input=studentImportInput.parse(r.body);return importStudents(input.rows,r.auth.organizationId);});

 app.get('/api/assessments',{preHandler:authenticate},r=>db.assessment.findMany({where:assessmentOrg(r.auth.organizationId),include:{unit:true,schoolClass:true,_count:{select:{key:true,sheets:true}}},orderBy:{assessmentDate:'desc'}}));
 app.get('/api/assessments/:id',{preHandler:authenticate},r=>db.assessment.findFirstOrThrow({where:{id:uuid.parse((r.params as {id:string}).id),...assessmentOrg(r.auth.organizationId)},include:{unit:true,schoolClass:{include:{students:true}},key:{orderBy:{question:'asc'}},sheets:{include:{student:true},orderBy:{createdAt:'desc'}}}}));
 app.post('/api/assessments',{preHandler:permit('ADMIN','MANAGER','TEACHER')},async r=>{const input=parseInput<AssessmentInput>(assessmentInput,r.body);if(input.scope==='NETWORK'){const networkUnit=await db.educationalUnit.findFirst({where:{organizationId:r.auth.organizationId,name:'Secretaria Municipal de Educação'}})??await db.educationalUnit.create({data:{organizationId:r.auth.organizationId,name:'Secretaria Municipal de Educação',code:'REDE'}});return createAssessment({...input,unitId:networkUnit.id,classId:null},r.auth.userId);}if(!input.unitId||!input.classId)throw new Error('Selecione a unidade e a turma.');await requireUnit(input.unitId,r.auth.organizationId);const klass=await requireClass(input.classId,r.auth.organizationId);if(klass.unitId!==input.unitId||klass.grade!==input.grade)throw new Error('A turma não corresponde à unidade e série selecionadas.');return createAssessment({...input,unitId:input.unitId,classId:input.classId},r.auth.userId);});
 app.put('/api/assessments/:id/answer-key',{preHandler:permit('ADMIN','MANAGER','TEACHER')},async r=>{const id=uuid.parse((r.params as {id:string}).id);await db.assessment.findFirstOrThrow({where:{id,...assessmentOrg(r.auth.organizationId)}});return saveAnswerKey(id,z.object({choices:z.array(z.enum(['A','B','C','D','E']))}).parse(r.body).choices);});
 app.post('/api/assessments/:id/sheets',{preHandler:permit('ADMIN','MANAGER','TEACHER')},async r=>{const id=uuid.parse((r.params as {id:string}).id);const a=await db.assessment.findFirstOrThrow({where:{id,...assessmentOrg(r.auth.organizationId)},include:{schoolClass:{include:{students:{where:{active:true}}}}}});const body=z.object({studentIds:z.array(uuid).optional(),allStudents:z.boolean().optional()}).default({}).parse(r.body??{});const eligible=a.schoolClass?.students??await db.student.findMany({where:{active:true,schoolClass:{grade:a.grade,unit:{organizationId:r.auth.organizationId},...(a.timeMode==='ALL'?{}:{timeMode:a.timeMode})}},select:{id:true}});const ids=body.allStudents?eligible.map(s=>s.id):(body.studentIds??[]);if(!ids.length)return createSheet(id);const valid=new Set(eligible.map(s=>s.id));if(ids.some(x=>!valid.has(x)))throw new Error('Há aluno fora do público desta avaliação.');return db.$transaction(ids.map(studentId=>db.answerSheet.upsert({where:{assessmentId_studentId:{assessmentId:id,studentId}},update:{},create:{assessmentId:id,studentId,templateId:'A4_LANDSCAPE_2UP_HORIZONTAL_V1',templateVersion:1}})));});
 app.get('/api/sheets/:id/pdf',{preHandler:authenticate},async(r,reply)=>{const id=uuid.parse((r.params as {id:string}).id);await db.answerSheet.findFirstOrThrow({where:{id,assessment:{unit:{organizationId:r.auth.organizationId}}}});return reply.type('application/pdf').header('Content-Disposition','attachment; filename="gabarito.pdf"').send(await sheetPdf(id));});

 app.get('/api/processings',{preHandler:authenticate},r=>db.readingProcessing.findMany({where:{sheet:{assessment:{unit:{organizationId:r.auth.organizationId}}}},include:{sheet:{include:{student:true,assessment:true}},_count:{select:{answers:true}}},orderBy:{createdAt:'desc'},take:100}));
 app.post('/api/processings',{preHandler:permit('ADMIN','MANAGER','TEACHER','OPERATOR')},async r=>{const file=await r.file();if(!file)throw new Error('Selecione um arquivo.');return processUpload(await file.toBuffer(),file.mimetype,r.auth.userId,r.auth.organizationId);});
 app.get('/api/processings/:id/review',{preHandler:authenticate},r=>db.readingProcessing.findFirstOrThrow({where:{id:uuid.parse((r.params as {id:string}).id),sheet:{assessment:{unit:{organizationId:r.auth.organizationId}}}},include:{answers:{orderBy:{question:'asc'}},sheet:{include:{student:true,assessment:{include:{key:true}}}}}}));
 app.get('/api/processings/:id/file',{preHandler:authenticate},async(r,reply)=>{const p=await db.readingProcessing.findFirstOrThrow({where:{id:uuid.parse((r.params as {id:string}).id),sheet:{assessment:{unit:{organizationId:r.auth.organizationId}}}}});const supabase=createClient(config.SUPABASE_URL,requiredSecret('SUPABASE_SECRET_KEY'),{auth:{persistSession:false}});const {data,error}=await supabase.storage.from('omr-private').download(p.storagePath);if(error)throw error;return reply.type(p.mimeType).send(Buffer.from(await data.arrayBuffer()));});
 app.patch('/api/processings/:id/review',{preHandler:permit('ADMIN','MANAGER','TEACHER','OPERATOR')},async r=>{const id=uuid.parse((r.params as {id:string}).id);await db.readingProcessing.findFirstOrThrow({where:{id,sheet:{assessment:{unit:{organizationId:r.auth.organizationId}}}}});const body=z.object({answers:z.array(z.object({question:z.number().int().positive(),choice:z.enum(['A','B','C','D','E']).nullable()}))}).parse(r.body);await db.$transaction(body.answers.map(a=>db.studentAnswer.update({where:{processingId_question:{processingId:id,question:a.question}},data:{finalChoice:a.choice,status:a.choice?'MARKED':'BLANK',reviewedBy:r.auth.userId,reviewedAt:new Date()}})));return db.readingProcessing.update({where:{id},data:{status:'READY'}});});
 app.post('/api/processings/:id/finalize',{preHandler:permit('ADMIN','MANAGER','TEACHER')},async r=>{const id=uuid.parse((r.params as {id:string}).id);const p=await db.readingProcessing.findFirstOrThrow({where:{id,sheet:{assessment:{unit:{organizationId:r.auth.organizationId}}}},include:{answers:{orderBy:{question:'asc'}},sheet:{include:{assessment:{include:{key:{orderBy:{question:'asc'}}}}}}}});if(!p.sheet)throw new Error('Processamento sem gabarito identificado.');if(p.sheet.assessment.key.length!==p.sheet.assessment.questionCount)throw new Error('Cadastre o gabarito oficial completo antes de corrigir.');const answers=p.answers.map(a=>({question:a.question,selected:a.finalChoice as Choice|null,marked:a.finalChoice?[a.finalChoice as Choice]:[],status:a.status,confidence:Number(a.confidence),fills:a.fills as never})) as RecognizedAnswer[];const grade=gradeAnswers(answers,p.sheet.assessment.key.map(k=>k.choice as Choice),Number(p.sheet.assessment.maxScore));const result=await db.result.upsert({where:{processingId:id},update:{...grade,finalizedBy:r.auth.userId,finalizedAt:new Date()},create:{sheetId:p.sheet.id,processingId:id,...grade,finalizedBy:r.auth.userId}});await db.readingProcessing.update({where:{id},data:{status:'FINALIZED'}});return result;});

 app.get('/api/results',{preHandler:authenticate},r=>db.result.findMany({where:{sheet:{assessment:{unit:{organizationId:r.auth.organizationId}}}},include:{sheet:{include:{student:true,assessment:{include:{unit:true,schoolClass:true}}}}},orderBy:{finalizedAt:'desc'}}));
 app.get('/api/reports/summary',{preHandler:authenticate},async r=>{const results=await db.result.findMany({where:{sheet:{assessment:{unit:{organizationId:r.auth.organizationId}}}},include:{sheet:{include:{student:true,assessment:{include:{unit:true,schoolClass:true}}}}}});const scores=results.map(x=>Number(x.score));return{count:results.length,average:scores.length?scores.reduce((a,b)=>a+b,0)/scores.length:0,highest:scores.length?Math.max(...scores):0,lowest:scores.length?Math.min(...scores):0,results};});
 app.get('/api/reports/results.csv',{preHandler:authenticate},async(r,reply)=>{const rows=await db.result.findMany({where:{sheet:{assessment:{unit:{organizationId:r.auth.organizationId}}}},include:{sheet:{include:{student:true,assessment:{include:{unit:true,schoolClass:true}}}}}});const csv=toCsv(rows.map(x=>({aluno:x.sheet.student?.name,unidade:x.sheet.assessment.unit.name,turma:x.sheet.assessment.schoolClass?.name??'Toda a rede',avaliacao:x.sheet.assessment.number,disciplina:x.sheet.assessment.subject,acertos:x.correct,erros:x.wrong,brancos:x.blank,invalidas:x.invalid,percentual:x.percentage,nota:x.score})));return reply.type('text/csv; charset=utf-8').header('Content-Disposition','attachment; filename="resultados.csv"').send(csv);});
}
