import {BarChart3,Building2,ChartNoAxesCombined,FileText,Printer} from 'lucide-react';
import {useEffect,useMemo,useState} from 'react';
import {Page} from '../components/Page';
import {api} from '../lib/api';
import {subjectLabel,type Result} from '../lib/types';

type ReportView='MANAGEMENT'|'CHARTS';
type ViewMode='NETWORK'|'UNIT';
type SummaryRow={name:string;students:number;sheets:number;correct:number;total:number;percentage:number;average:number;highest:number;lowest:number};
const all='ALL';
const classNameOf=(item:Result)=>item.sheet.student?.schoolClass?.name??item.sheet.assessment.schoolClass?.name??'Toda a rede';
const unitNameOf=(item:Result)=>item.sheet.student?.schoolClass?.unit?.name??item.sheet.assessment.unit.name;

function summarize(name:string,items:Result[]):SummaryRow{
 const scores=items.map(item=>Number(item.score)),correct=items.reduce((sum,item)=>sum+item.correct,0),total=items.reduce((sum,item)=>sum+item.total,0);
 return{name,students:new Set(items.map(item=>item.sheet.student?.id).filter(Boolean)).size,sheets:items.length,correct,total,percentage:total?correct/total*100:0,average:scores.length?scores.reduce((sum,value)=>sum+value,0)/scores.length:0,highest:scores.length?Math.max(...scores):0,lowest:scores.length?Math.min(...scores):0};
}
function groupSummary(items:Result[],nameOf:(item:Result)=>string){const groups=new Map<string,Result[]>();for(const item of items){const name=nameOf(item);groups.set(name,[...(groups.get(name)??[]),item])}return[...groups.entries()].map(([name,values])=>summarize(name,values)).sort((a,b)=>b.percentage-a.percentage||a.name.localeCompare(b.name,'pt-BR'))}

export function Reports(){
 const [items,setItems]=useState<Result[]>([]),[view,setView]=useState<ReportView>('MANAGEMENT'),[mode,setMode]=useState<ViewMode>('NETWORK'),[assessment,setAssessment]=useState(all),[grade,setGrade]=useState(all),[schoolClass,setSchoolClass]=useState(all),[subject,setSubject]=useState(all),[message,setMessage]=useState('');
 useEffect(()=>{api<Result[]>('/api/results').then(setItems).catch(error=>setMessage(error.message))},[]);
 const assessmentOptions=useMemo(()=>[...new Set(items.map(item=>item.sheet.assessment.number))].sort(),[items]);
 const gradeOptions=useMemo(()=>[...new Set(items.map(item=>item.sheet.assessment.grade))].sort((a,b)=>a-b),[items]);
 const subjectOptions=useMemo(()=>[...new Set(items.map(item=>item.sheet.assessment.subject))].sort(),[items]);
 const classOptions=useMemo(()=>[...new Set(items.filter(item=>(assessment===all||item.sheet.assessment.number===assessment)&&(grade===all||item.sheet.assessment.grade===Number(grade))&&(subject===all||item.sheet.assessment.subject===subject)).map(classNameOf))].sort((a,b)=>a.localeCompare(b,'pt-BR',{numeric:true})),[items,assessment,grade,subject]);
 useEffect(()=>{if(schoolClass!==all&&!classOptions.includes(schoolClass))setSchoolClass(all)},[classOptions,schoolClass]);
 const filtered=useMemo(()=>items.filter(item=>(assessment===all||item.sheet.assessment.number===assessment)&&(grade===all||item.sheet.assessment.grade===Number(grade))&&(schoolClass===all||classNameOf(item)===schoolClass)&&(subject===all||item.sheet.assessment.subject===subject)),[items,assessment,grade,schoolClass,subject]);
 const totals=useMemo(()=>summarize('Total',filtered),[filtered]);
 const rows=useMemo(()=>mode==='NETWORK'?[summarize('Rede Municipal de Ensino',filtered)]:groupSummary(filtered,unitNameOf),[filtered,mode]);
 const unitRows=useMemo(()=>groupSummary(filtered,unitNameOf),[filtered]);
 const subjectRows=useMemo(()=>groupSummary(filtered,item=>subjectLabel(item.sheet.assessment.subject)),[filtered]);
 const assessmentRows=useMemo(()=>groupSummary(filtered,item=>item.sheet.assessment.number),[filtered]);
 const scoreBands=useMemo(()=>{const bands=[{name:'Muito Crítico',range:'0% a <40%',count:0,color:'bg-[#b94343]'},{name:'Crítico',range:'40% a <60%',count:0,color:'bg-[#d9a441]'},{name:'Satisfatório',range:'60% ou mais',count:0,color:'bg-forest'}];for(const item of filtered){const value=Number(item.percentage),index=value<40?0:value<60?1:2;bands[index].count++}return bands},[filtered]);
 const filterDescription=`Avaliação: ${assessment===all?'Todas':assessment} | Série: ${grade===all?'Todas':`${grade}º ano`} | Turma: ${schoolClass===all?'Todas':schoolClass} | Disciplina: ${subject===all?'Todas':subjectLabel(subject)}`;
 function printReport(){document.body.classList.add('report-printing');const cleanup=()=>document.body.classList.remove('report-printing');window.addEventListener('afterprint',cleanup,{once:true});window.print();setTimeout(cleanup,1500)}

 return <Page eyebrow="Análise" title="Relatórios" description="Selecione a visão e os filtros para consultar, analisar ou imprimir o desempenho.">
  <section className="report-controls card mb-5">
   <div className="grid gap-4 md:grid-cols-2"><ViewButton active={view==='MANAGEMENT'} icon={<FileText/>} title="Relatórios Gerenciais" description="Tabelas consolidadas da rede e das unidades." onClick={()=>setView('MANAGEMENT')}/><ViewButton active={view==='CHARTS'} icon={<ChartNoAxesCombined/>} title="Relatórios em Gráficos" description="Dashboard visual para análise de desempenho." onClick={()=>setView('CHARTS')}/></div>
   {view==='MANAGEMENT'&&<div className="mt-4 grid gap-3 md:grid-cols-2"><ModeButton active={mode==='NETWORK'} icon={<BarChart3/>} title="Desempenho Geral da Rede" description="Consolida todas as unidades selecionadas." onClick={()=>setMode('NETWORK')}/><ModeButton active={mode==='UNIT'} icon={<Building2/>} title="Desempenho por Unidade" description="Compara cada unidade educacional." onClick={()=>setMode('UNIT')}/></div>}
   <div className="mt-5 grid gap-4 md:grid-cols-2 xl:grid-cols-4"><Filter label="Avaliação" value={assessment} onChange={setAssessment} options={assessmentOptions.map(value=>({value,label:value}))}/><Filter label="Série" value={grade} onChange={setGrade} options={gradeOptions.map(value=>({value:String(value),label:`${value}º ano`}))}/><Filter label="Turma" value={schoolClass} onChange={setSchoolClass} options={classOptions.map(value=>({value,label:value}))}/><Filter label="Disciplina" value={subject} onChange={setSubject} options={subjectOptions.map(value=>({value,label:subjectLabel(value)}))}/></div>
   <div className="mt-5 flex justify-end"><button className="btn inline-flex items-center gap-2" disabled={!filtered.length} onClick={printReport}><Printer size={18}/> Imprimir / Salvar PDF</button></div>
  </section>
  {view==='MANAGEMENT'?<ManagementReport mode={mode} rows={rows} totals={totals} filterDescription={filterDescription} message={message}/>:<ChartsDashboard totals={totals} unitRows={unitRows} subjectRows={subjectRows} assessmentRows={assessmentRows} scoreBands={scoreBands} filterDescription={filterDescription} message={message}/>}\r\n </Page>;
}

function ManagementReport({mode,rows,totals,filterDescription,message}:{mode:ViewMode;rows:SummaryRow[];totals:SummaryRow;filterDescription:string;message:string}){return <section className="report-sheet card"><ReportHeader title={mode==='NETWORK'?'Desempenho Geral da Rede':'Desempenho por Unidade'} description={filterDescription}/><Metrics totals={totals}/><div className="overflow-x-auto"><table className="report-table w-full text-left"><thead><tr className="border-b-2 border-black"><th className="pb-2">{mode==='NETWORK'?'Abrangência':'Unidade'}</th><th>Alunos</th><th>Gabaritos</th><th>Acertos</th><th>Total de questões</th><th>% de acertos</th><th>Nota média</th><th>Maior nota</th><th>Menor nota</th></tr></thead><tbody>{rows.map(row=><tr className="border-b" key={row.name}><td className="py-3 font-semibold">{row.name}</td><td>{row.students}</td><td>{row.sheets}</td><td>{row.correct}</td><td>{row.total}</td><td>{formatPercent(row.percentage)}</td><td>{formatNumber(row.average)}</td><td>{formatNumber(row.highest)}</td><td>{formatNumber(row.lowest)}</td></tr>)}</tbody></table>{!totals.sheets&&<Empty message={message}/>}</div><ReportFooter/></section>}

function ChartsDashboard({totals,unitRows,subjectRows,assessmentRows,scoreBands,filterDescription,message}:{totals:SummaryRow;unitRows:SummaryRow[];subjectRows:SummaryRow[];assessmentRows:SummaryRow[];scoreBands:Array<{name:string;range:string;count:number;color:string}>;filterDescription:string;message:string}){return <section className="report-sheet min-w-0"><div className="card min-w-0"><ReportHeader title="Dashboard de Desempenho" description={filterDescription}/><Metrics totals={totals}/>{!totals.sheets&&<Empty message={message}/>}</div>{totals.sheets>0&&<div className="mt-5 grid min-w-0 grid-cols-1 gap-5 2xl:grid-cols-2"><ChartCard title="Aproveitamento por unidade" subtitle="Percentual de acertos por unidade educacional"><HorizontalBars rows={unitRows}/></ChartCard><ChartCard title="Desempenho por disciplina" subtitle="Comparação direta do percentual de acertos"><HorizontalBars rows={subjectRows}/></ChartCard><ChartCard title="Desempenho por avaliação" subtitle="Evolução entre as avaliações selecionadas"><HorizontalBars rows={assessmentRows}/></ChartCard><ChartCard title="Distribuição dos estudantes" subtitle="Quantidade de resultados por faixa de aproveitamento"><DistributionChart rows={scoreBands}/></ChartCard></div>}<ReportFooter/></section>}

function Metrics({totals}:{totals:SummaryRow}){return <div className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4"><Metric label="Gabaritos lidos" value={totals.sheets}/><Metric label="Alunos avaliados" value={totals.students}/><Metric label="% de acertos" value={formatPercent(totals.percentage)}/><Metric label="Nota média" value={formatNumber(totals.average)}/></div>}
function HorizontalBars({rows}:{rows:SummaryRow[]}){return <div className="min-w-0 space-y-4">{rows.map(row=><div className="min-w-0" key={row.name}><div className="mb-1.5 flex items-start justify-between gap-3 text-sm"><span className="min-w-0 break-words font-semibold" title={row.name}>{row.name}</span><strong className="shrink-0 text-forest">{formatPercent(row.percentage)}</strong></div><div className="h-3 w-full overflow-hidden rounded-full bg-paper"><div className="h-full rounded-full bg-forest transition-[width]" style={{width:`${Math.max(row.percentage?2:0,Math.min(100,row.percentage))}%`}}/></div><div className="mt-1 break-words text-[11px] text-black/45">{row.sheets} gabarito(s) · média {formatNumber(row.average)}</div></div>)}</div>}
function DistributionChart({rows}:{rows:Array<{name:string;range:string;count:number;color:string}>}){const total=rows.reduce((sum,row)=>sum+row.count,0);return <div className="grid min-w-0 grid-cols-1 gap-3 sm:grid-cols-3">{rows.map(row=>{const percentage=total?row.count/total*100:0;return <div className="min-w-0 rounded-xl border border-black/10 bg-white p-4" key={row.name}><div className="flex items-start justify-between gap-3"><div className="min-w-0"><strong className="block break-words text-sm">{row.name}</strong><span className="block text-xs text-black/50">{row.range}</span></div><strong className="shrink-0 text-xl text-forest">{row.count}</strong></div><div className="mt-4 h-3 w-full overflow-hidden rounded-full bg-paper"><div className={`h-full rounded-full transition-[width] ${row.color}`} style={{width:`${Math.max(percentage?3:0,percentage)}%`}}/></div><div className="mt-2 flex flex-wrap justify-between gap-2 text-[11px] text-black/50"><span>{row.count} resultado(s)</span><span>{formatPercent(percentage)}</span></div></div>})}</div>}
function ViewButton({active,icon,title,description,onClick}:{active:boolean;icon:React.ReactNode;title:string;description:string;onClick:()=>void}){return <button className={`rounded-2xl border-2 p-5 text-left transition ${active?'border-forest bg-forest text-white shadow-sm':'border-black/10 hover:border-forest/40'}`} onClick={onClick}>{icon}<strong className="mt-3 block text-lg">{title}</strong><span className={`mt-1 block text-sm ${active?'text-white/70':'text-black/50'}`}>{description}</span></button>}
function ModeButton({active,icon,title,description,onClick}:{active:boolean;icon:React.ReactNode;title:string;description:string;onClick:()=>void}){return <button className={`rounded-xl border p-4 text-left transition ${active?'border-forest bg-mint text-forest':'hover:border-forest/40'}`} onClick={onClick}><span className="flex items-center gap-3">{icon}<strong>{title}</strong></span><span className="mt-1 block pl-9 text-xs opacity-65">{description}</span></button>}
function Filter({label,value,onChange,options}:{label:string;value:string;onChange:(value:string)=>void;options:Array<{value:string;label:string}>}){return <label><span className="label">{label}</span><select className="field" value={value} onChange={event=>onChange(event.target.value)}><option value={all}>Todas</option>{options.map(option=><option value={option.value} key={option.value}>{option.label}</option>)}</select></label>}
function ChartCard({title,subtitle,children}:{title:string;subtitle:string;children:React.ReactNode}){return <article className="card min-w-0 overflow-hidden break-inside-avoid"><h3 className="break-words text-lg font-bold">{title}</h3><p className="mb-5 mt-1 break-words text-xs text-black/45">{subtitle}</p>{children}</article>}
function ReportHeader({title,description}:{title:string;description:string}){return <header className="report-title mb-5 border-b pb-4"><div className="text-xs font-bold uppercase tracking-widest text-forest">Secretaria Municipal de Educação de Uberaba</div><h2 className="mt-2 text-2xl font-bold">{title}</h2><p className="mt-1 text-sm">{description}</p><p className="mt-1 text-xs text-black/50">Emitido em {new Date().toLocaleString('pt-BR')}</p></header>}
function ReportFooter(){return <footer className="report-footer mt-8 hidden border-t pt-3 text-center text-xs">Sistema Avalia - Relatório de desempenho escolar</footer>}
function Metric({label,value}:{label:string;value:string|number}){return <div className="rounded-xl bg-paper p-4"><strong className="text-2xl">{value}</strong><span className="block text-xs text-black/50">{label}</span></div>}
function Empty({message}:{message:string}){return <p className="py-10 text-center text-black/45">{message||'Nenhum resultado encontrado para os filtros selecionados.'}</p>}
const formatNumber=(value:number)=>value.toLocaleString('pt-BR',{maximumFractionDigits:2});
const formatPercent=(value:number)=>`${formatNumber(value)}%`;
