import {MAX_STUDENT_IMPORT_ROWS,STUDENT_IMPORT_BATCH_SIZE} from '@omr/core/imports';
import {ChevronDown,Download,Upload,Users as UsersIcon} from 'lucide-react';
import {Fragment,useEffect,useMemo,useState} from 'react';
import {Page} from '../components/Page';
import {api} from '../lib/api';
import {downloadStudentTemplate,parseStudentCsv,type StudentImportRow} from '../lib/studentImport';
import type {SchoolClass,Unit} from '../lib/types';

type StudentRow={id:string;name:string;registration?:string;classId:string};
const timeLabel=(value:'PARTIAL'|'FULL')=>value==='FULL'?'Integral':'Parcial';

export function Students(){
 const [classes,setClasses]=useState<SchoolClass[]>([]),[groups,setGroups]=useState<SchoolClass[]>([]),[units,setUnits]=useState<Unit[]>([]),[studentsByClass,setStudentsByClass]=useState<Record<string,StudentRow[]>>({});
 const [unitId,setUnitId]=useState(''),[grade,setGrade]=useState(1),[classId,setClassId]=useState('');
 const [query,setQuery]=useState(''),[message,setMessage]=useState(''),[importRows,setImportRows]=useState<StudentImportRow[]>([]),[importing,setImporting]=useState(false),[loadingClass,setLoadingClass]=useState('');
 const [expandedClasses,setExpandedClasses]=useState<Set<string>>(new Set());
 const load=()=>Promise.all([api<SchoolClass[]>('/api/classes'),api<Unit[]>('/api/units')]).then(([classRows,unitRows])=>{setClasses(classRows);setGroups(classRows);setUnits(unitRows);setStudentsByClass({});setExpandedClasses(new Set())}).catch(error=>setMessage(error.message));
 useEffect(()=>{void load()},[]);
 useEffect(()=>{const term=query.trim();if(!term){setGroups(classes);setStudentsByClass({});setExpandedClasses(new Set());return}const timer=setTimeout(()=>{api<SchoolClass[]>(`/api/student-groups?query=${encodeURIComponent(term)}`).then(rows=>{setGroups(rows);setStudentsByClass({});setExpandedClasses(new Set())}).catch(error=>setMessage(error.message))},300);return()=>clearTimeout(timer)},[query,classes]);
 const availableClasses=useMemo(()=>classes.filter(item=>item.unitId===unitId&&item.grade===grade).sort((a,b)=>a.name.localeCompare(b.name,'pt-BR',{numeric:true})||timeLabel(a.timeMode).localeCompare(timeLabel(b.timeMode),'pt-BR')),[classes,unitId,grade]);

 async function submit(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=event.currentTarget;try{await api('/api/students',{method:'POST',body:JSON.stringify(Object.fromEntries(new FormData(form)))});form.reset();setClassId('');setMessage('Aluno cadastrado com sucesso.');await load()}catch(error){setMessage((error as Error).message)}}
 async function chooseFile(file?:File){if(!file)return;try{const rows=parseStudentCsv(await file.text());setImportRows(rows);setMessage(`${rows.length} aluno(s) pronto(s) para importação.`)}catch(error){setImportRows([]);setMessage((error as Error).message)}}
 async function importFile(){if(!importRows.length)return;try{setImporting(true);let imported=0;for(let offset=0;offset<importRows.length;offset+=STUDENT_IMPORT_BATCH_SIZE){const batch=importRows.slice(offset,offset+STUDENT_IMPORT_BATCH_SIZE);setMessage(`Importando ${Math.min(offset+batch.length,importRows.length).toLocaleString('pt-BR')} de ${importRows.length.toLocaleString('pt-BR')} alunos…`);const result=await api<{imported:number}>('/api/students/import',{method:'POST',body:JSON.stringify({rows:batch})});imported+=result.imported}setImportRows([]);setMessage(`${imported.toLocaleString('pt-BR')} aluno(s) importado(s) com sucesso.`);await load()}catch(error){setMessage((error as Error).message)}finally{setImporting(false)}}
 async function toggleClass(id:string){if(expandedClasses.has(id)){setExpandedClasses(current=>{const next=new Set(current);next.delete(id);return next});return}setLoadingClass(id);try{const term=query.trim(),students=await api<StudentRow[]>(`/api/classes/${id}/students${term?`?query=${encodeURIComponent(term)}`:''}`);setStudentsByClass(current=>({...current,[id]:students}));setExpandedClasses(current=>new Set(current).add(id))}catch(error){setMessage((error as Error).message)}finally{setLoadingClass('')}}

 return <Page eyebrow="Cadastros" title="Alunos" description="Cadastre estudantes com unidade, série, turma e tempo ou importe uma lista padronizada.">
  <div className="grid gap-5 xl:grid-cols-[400px_1fr]"><div className="space-y-5">
   <form className="card grid gap-4" onSubmit={submit}><h2 className="text-lg font-bold">Novo aluno</h2><label><span className="label">Nome completo</span><input className="field" name="name" required/></label><label><span className="label">Matrícula</span><input className="field" name="registration"/></label><label><span className="label">Unidade</span><select className="field" value={unitId} onChange={event=>{setUnitId(event.target.value);setClassId('')}} required><option value="">Selecione</option>{units.filter(item=>item.code!=='REDE').map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label><label><span className="label">Série</span><select className="field" value={grade} onChange={event=>{setGrade(Number(event.target.value));setClassId('')}}>{Array.from({length:9},(_,index)=><option value={index+1} key={index}>{index+1}º ano</option>)}</select></label><label><span className="label">Turma/Tempo</span><select className="field" name="classId" value={classId} onChange={event=>setClassId(event.target.value)} required disabled={!unitId}><option value="">{unitId?'Selecione':'Selecione a unidade'}</option>{availableClasses.map(item=><option value={item.id} key={item.id}>{item.name} - {timeLabel(item.timeMode)}</option>)}</select></label><button className="btn" disabled={!classId}>Cadastrar aluno</button></form>
   <section className="card"><div className="flex items-center gap-2"><Upload className="text-forest"/><h2 className="text-lg font-bold">Importar alunos</h2></div><p className="mt-2 text-sm text-black/50">Arquivo CSV com nome, matrícula, unidade, série, turma e tempo. Limite de {MAX_STUDENT_IMPORT_ROWS.toLocaleString('pt-BR')} alunos por arquivo.</p><button type="button" className="mt-4 flex items-center gap-2 text-sm font-semibold text-forest" onClick={downloadStudentTemplate}><Download size={17}/> Baixar modelo de exemplo</button><label className="mt-4 block cursor-pointer rounded-xl border border-dashed border-black/20 p-4 text-center"><input className="hidden" type="file" accept=".csv,text/csv" onChange={event=>void chooseFile(event.target.files?.[0])}/><Upload className="mx-auto text-black/40"/><strong className="mt-2 block">Selecionar arquivo CSV</strong>{importRows.length>0&&<span className="text-sm text-forest">{importRows.length} linha(s) validada(s)</span>}</label><button className="btn mt-3 w-full disabled:opacity-50" disabled={!importRows.length||importing} onClick={importFile}>{importing?'Importando…':'Importar alunos'}</button></section>
   {message&&<div className="card text-sm">{message}</div>}
  </div><div className="card"><div className="mb-4 flex items-center gap-3"><UsersIcon className="shrink-0 text-forest"/><div className="flex-1"><input className="field" placeholder="Buscar por aluno, matrícula, unidade ou turma…" value={query} onChange={event=>setQuery(event.target.value)}/></div></div><div className="overflow-x-auto"><table className="w-full min-w-[720px] text-left text-sm"><thead><tr className="border-b text-black/45"><th className="pb-3">Unidade</th><th>Série</th><th>Turma</th><th>Tempo</th><th className="text-right">Quantidade de alunos</th><th className="w-10"><span className="sr-only">Expandir</span></th></tr></thead><tbody>{groups.map(schoolClass=>{const expanded=expandedClasses.has(schoolClass.id),students=studentsByClass[schoolClass.id]??[];return <Fragment key={schoolClass.id}><tr className="cursor-pointer border-b transition hover:bg-paper/70" onClick={()=>void toggleClass(schoolClass.id)} aria-expanded={expanded}><td className="py-4 font-semibold">{schoolClass.unit.name}</td><td>{schoolClass.grade}º ano</td><td><span className="rounded-lg bg-paper px-3 py-1 font-semibold">{schoolClass.name}</span></td><td>{timeLabel(schoolClass.timeMode)}</td><td className="text-right font-bold">{(schoolClass._count?.students??0).toLocaleString('pt-BR')}</td><td><ChevronDown className={`transition ${expanded?'rotate-180':''}`} size={18}/></td></tr>{expanded&&<tr className="border-b bg-paper/45"><td colSpan={6} className="p-0"><div className="grid gap-2 p-4 sm:grid-cols-2 2xl:grid-cols-3">{students.map(student=><div className="rounded-xl border border-black/10 bg-white px-4 py-3" key={student.id}><strong className="block">{student.name}</strong><small className="text-black/50">Matrícula: {student.registration||'não informada'}</small></div>)}{!students.length&&<p className="p-3 text-black/45">Nenhum aluno encontrado nesta turma.</p>}</div></td></tr>}{loadingClass===schoolClass.id&&<tr><td colSpan={6} className="p-3 text-center text-sm text-forest">Carregando alunos…</td></tr>}</Fragment>})}</tbody></table>{!groups.length&&<p className="py-8 text-center text-black/45">Nenhuma turma ou aluno encontrado.</p>}</div></div></div>
 </Page>
}
